In [1]:
import numpy as np

In [2]:
m = np.matrix([
    [0.7, 0.2, 0.1],
    [0, 0.6, 0.4],
    [0.5, 0, 0.5]
])

m**2

matrix([[0.54, 0.26, 0.2 ],
        [0.2 , 0.36, 0.44],
        [0.6 , 0.1 , 0.3 ]])

In [3]:
m = np.matrix([
    [3/4, 1/4],
    [1/3, 2/3]
])

m**2

matrix([[0.64583333, 0.35416667],
        [0.47222222, 0.52777778]])

In [4]:
from scipy.special import comb

In [5]:
4*2/comb(6, 2) + 4*3/comb(6,2)/2 + 2*1/comb(6,2)/2

1.0

Dois estados $i$ e $j$ pertencem a mesma classe se e somente se $i$ é acessível por $j$ e $j$ é acessível por $i$.

$i$ é acessível por $j$ se $P(X_k=i | X_0=j) > 0$ para algum $k$

Considere dois estados genéricos $i$ e $j$ tal que $i < j$. Ou seja, entre $i$ e $j$ existem os estados $i+1, i+2, i+3, \dots, j$. São $k = j-i$ estados intermediários, de forma que conseguimos chegar em $j$, partindo de $i$, em no mínimo k passos.

Sabemos que

$$
P(X_k=i | X_0=j) \ge P(X_k=i | X_0=j, X_1=j-1, \dots, X_{k-1}=i+1) \times \ 
$$
$$
\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \times P(X_1=j-1, \dots, X_{k-1}=i+1 | X_0=j) =
$$
$$
= P(X_k=i | X_{k-1}=i+1) \cdot P(X_1=j-1, \dots, X_{k-1}=i+1  | X_0=j) =
$$
$$
P(j,j-1) \cdot P(j-1,j-2) \cdot P(j-2, j-3) \cdot \dots \cdot P(i+1, i) =
$$
$$
(1-p)^k
$$

E $(1-p)^k > 0$ desde que $p \ne 1$. Portanto, se $p \ne 1$ $i$ é acessível por $j$.

Utilizando raciocínio análogo, provamos que $j$ é acessível por $i$ desde que $p \ne 0$.

Logo, quaisquer dois estados $i$ e $j$ pertencem à mesma classe se, e somente se, $p \ne 0$ e $p \ne 1$.

In [7]:
P = np.matrix([
    [1/3, 2/3, 0],
    [1/2, 0, 1/2],
    [1/6, 1/3, 1/2]
])

P**64

matrix([[0.33333333, 0.33333333, 0.33333333],
        [0.33333333, 0.33333333, 0.33333333],
        [0.33333333, 0.33333333, 0.33333333]])

In [9]:
P = np.matrix([
    [0,0,0,1],
    [1/4,1/4,1/4,1/4],
    [0,1/3,0,2/3],
    [1/3,1/3,1/3,0]
])

print(P**64)
print(np.array([3/16, 1/4, 3/16, 3/8]))

[[0.1875 0.25   0.1875 0.375 ]
 [0.1875 0.25   0.1875 0.375 ]
 [0.1875 0.25   0.1875 0.375 ]
 [0.1875 0.25   0.1875 0.375 ]]
[0.1875 0.25   0.1875 0.375 ]
